name: Docker Image CI

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: setup versioning
      id: vars
      run: |
        build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        build_version="$(date -u +'%Y-%m-%d')"
        echo "build_date=$build_date" >> $GITHUB_OUTPUT
        echo "build_version=$build_version" >> $GITHUB_OUTPUT
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.standalone_spark_3.1.1
        build-args: |
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_VERSION=${{ steps.vars.outputs.build_version }}
        push: true
        tags: |
          cyijun/bigdata_dockers:standalone_spark_3.1.1-latest
          cyijun/bigdata_dockers:standalone_spark_3.1.1-${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64
